language: java

addons:
  sonarcloud:
    organization: "keyneloui"
    token:
      secure: bf02627e569037c8cb21e44d13c4a627af977489
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'   
    
#jobs:
#  include:
    #- stage: pre-build
     # script: mvn clean
  
    #- stage: test
    #  script: mvn test org.jacoco:jacoco-maven-plugin:prepare-agent
    
    #- stage: build
     # script: mvn install
      
    #- stage: quality
     # script: mvn sonar:sonar

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar 
  slack: javafullstackgroup:cU6yGmSyVRshhITnnXELpBug
  

  
  
